### ISSUE TITLE
Wrong error contents for TurnOff()

### ISSUE THREAD

**Issue by maclermo** [jaedle/golang-tplink-hs100#123]
Hi,

Thanks for this nice library that simply works.

I was scratching my head as to why my unit tests were failing while testing a "turn off" scenario.

Please take a look at the following:

https://github.com/jaedle/golang-tplink-hs100/blob/fd6397fd1373c8324ff596d097f11ab01989e71d/pkg/hs100/hs100.go#L72

The error message should be `error on sending turn off command for device`

Thanks!

**Comment by jaedle** [comment]
Hey 👋 

thanks for the feedback, I hope I will come around tomorrow fixing this, thanks!

**Comment by jaedle** [comment]
Thanks @andrewmarklloyd for your contribution :pray:

**Comment by andrewmarklloyd** [comment]
No problem thanks for the great library!
