### ISSUE TITLE
Command go get github.com/jaedle/golang-tplink-hs100 return an error

### ISSUE THREAD

**Issue by gdo** [jaedle/golang-tplink-hs100#9]
>  go get github.com/jaedle/golang-tplink-hs100
Display
> can't load package: package github.com/jaedle/golang-tplink-hs100: no Go files in /home/gdo/go/src/github.com/jaedle/golang-tplink-hs100

**Comment by jaedle** [comment]
Thanks for raising this issue. 

I highly recommend using go modules with this library. 
If you don't want to you should be fine with `go get github.com/jaedle/golang-tplink-hs100/...`

**Comment by jaedle** [comment]
See #10
